### ISSUE TITLE
Question/Feature request: Multiple documentations

### ISSUE THREAD

**Issue by bernhardh** [JustSteveKing/laravel-stoplight-elements#11]
Is there a way to use this for multiple different API's in the same project?

**Comment by JustSteveKing** [comment]
Hey @bernhardh !

So the way this works is that a view is rendered on a route. You could register your own routes that render the same view dynamically setting the `config('stoplight.openapi.path')` before rendering which would allow you to implement this

**Comment by bernhardh** [comment]
Thanks for the feedback!
